
import { GoogleGenAI, Type } from "@google/genai";

export class GeminiService {
  private getClient() {
    // Process.env.API_KEY is handled externally/injected
    return new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  /**
   * Generates high-quality images using Gemini 3 Pro Image.
   * Note: This model REQUIRES the user to select their own API key via window.aistudio.openSelectKey().
   */
  async generateImage(prompt: string, aspectRatio: string = "1:1") {
    const ai = this.getClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: aspectRatio as any,
          imageSize: "1K"
        }
      }
    });

    const imagePart = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
    if (imagePart?.inlineData?.data) {
      return `data:image/png;base64,${imagePart.inlineData.data}`;
    }
    
    const textPart = response.candidates?.[0]?.content?.parts.find(p => p.text);
    if (textPart?.text) {
        throw new Error(`AI Note: ${textPart.text}`);
    }

    throw new Error("No image data generated by the model.");
  }

  /**
   * Optimizes a prompt using Google Search trends and then generates a background image.
   */
  async generateSmartBackground(prompt: string) {
    const ai = this.getClient();
    
    // 1. Research trends and visual accuracy using Google Search
    const research = await this.researchTopic(`latest aesthetic trends and visual details for a high quality 4k background of: ${prompt}`);
    
    // 2. Use Gemini 3 Flash to generate an optimized artistic prompt based on research
    const optimizationRes = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Based on this visual research: "${research.text}", create a highly detailed, professional, and artistic image prompt (in English) for a background that represents: "${prompt}". The background should be suitable for a professional design project. Return ONLY the prompt text.`,
    });
    
    const optimizedPrompt = optimizationRes.text || prompt;

    // 3. Generate the actual high-quality image
    return this.generateImage(optimizedPrompt, "16:9");
  }

  /**
   * Remixes an existing image using Gemini 2.5 Flash Image.
   */
  async remixImage(base64Image: string, style: string) {
    const ai = this.getClient();
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          { 
            inlineData: { 
              mimeType: 'image/jpeg', 
              data: base64Image 
            } 
          },
          { text: `Remix this image using the following style instructions: ${style}. Maintain the core composition but transform the artistic direction.` }
        ]
      }
    });

    const imagePart = response.candidates?.[0]?.content?.parts.find(p => p.inlineData);
    if (imagePart?.inlineData?.data) {
      return `data:image/png;base64,${imagePart.inlineData.data}`;
    }
    throw new Error("Failed to remix image.");
  }

  /**
   * Uses Google Search grounding to research design trends and facts.
   */
  async researchTopic(topic: string) {
    const ai = this.getClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Investiga y resume las tendencias actuales de diseño, colores populares o datos relevantes para: "${topic}". Responde de forma concisa en español para ayudar a un diseñador gráfico.`,
      config: {
        tools: [{ googleSearch: {} }]
      }
    });

    const sources: { title?: string, uri: string }[] = [];
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    if (chunks) {
      chunks.forEach((chunk: any) => {
        if (chunk.web) {
          sources.push({ title: chunk.web.title, uri: chunk.web.uri });
        }
      });
    }

    return {
      text: response.text || "No se encontró información.",
      sources
    };
  }

  /**
   * Generates catchy text ideas using Gemini 3 Flash.
   */
  async generateTextIdeas(topic: string, type: string) {
    const ai = this.getClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Generate 5 unique and catchy ${type} ideas in Spanish for: "${topic}". Return ONLY a JSON array of strings.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: { type: Type.STRING }
        }
      }
    });
    return JSON.parse(response.text || '[]');
  }

  /**
   * Generates a color palette using Gemini 3 Flash.
   */
  async generatePalette(theme: string) {
    const ai = this.getClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: `Design a professional color palette (5 hex codes) for the theme: "${theme}". Return ONLY a JSON array of hex strings.`,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: { type: Type.STRING }
        }
      }
    });
    return JSON.parse(response.text || '[]');
  }

  /**
   * Analyzes design layout and provides tips using Gemini 3 Flash.
   */
  async analyzeDesign(base64Image: string) {
    const ai = this.getClient();
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: {
        parts: [
          { inlineData: { mimeType: 'image/jpeg', data: base64Image } },
          { text: "Analiza este diseño. Da 3 consejos profesionales breves y sugiere un título. Responde en español." }
        ]
      }
    });
    return response.text;
  }
}
